{
 "title": "Aquarium Status",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "InfluxDB", "query": "influxdb" },
   {
    "name": "Apex",
    "label": "Apex",
    "query": "show tag values from \"neptune_apex\" with key = \"source\""
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "farenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Tmp" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Apex$/" }
     ]
    }
   ]
  },
  {
   "title": "pH",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "pH" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Apex$/" }
     ]
    }
   ]
  },
  {
   "title": "EB8 Current",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Amp_4" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Apex$/" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "aquarium_power_watts" }
     ]
    }
   ]
  },
  {
   "title": "Chihiros",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "WiFi Bridge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Chihiros" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Apex$/" }
     ]
    }
   ]
  },
  {
   "title": "Pumps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Pumps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Pumps" }
     ]
    }
   ]
  },
  {
   "title": "Heater_EB8",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Heater_EB8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$Apex$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Heater" }
     ]
    }
   ]
  },
  {
   "title": "Skimmer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Skimmer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Skimmer" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Apex$/" }
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "CO2" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Apex$/" }
     ]
    }
   ]
  },
  {
   "title": "ATO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ATO",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "query": "SELECT last(\"state_code\") FROM \"neptune_apex\" WHERE (\"name\" = 'WiFiBridge') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "ATO" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Apex$/" }
     ]
    }
   ]
  },
  {
   "title": "Aquarium Temperature",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "probe_type", "operator": "=", "value": "Temp" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Apex$/" }
     ]
    },
    {
     "alias": "Heater",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*(-1)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Heater" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Apex$/" }
     ]
    }
   ]
  },
  {
   "title": "Aquarium pH",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "targets": [
    {
     "alias": "pH",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "probe_type", "operator": "=", "value": "pH" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Apex$/" }
     ]
    },
    {
     "alias": "CO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "state_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "CO2" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Apex$/" }
     ]
    }
   ]
  },
  {
   "title": "Aquarium Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "W",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "aquarium_power_watts" }
     ]
    }
   ]
  },
  {
   "title": "EB8 Current",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "EB8 Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "neptune_apex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Amp_4" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$Apex$/" }
     ]
    }
   ]
  }
 ]
}